# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('article', models.TextField()),
                ('shor_article', models.TextField()),
                ('publishe', models.DateTimeField(blank=True, default=False)),
            ],
            options={
                'db_table': 'ARTICLE',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SKILL',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('fio', models.CharField(max_length=250)),
                ('years', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('about', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='me.Article')),
                ('skills', models.ManyToManyField(to='me.Skill')),
            ],
            options={
                'db_table': 'PERSONA',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='me.Article')),
                ('links', models.CharField(max_length=200)),
                ('skills', models.ManyToManyField(to='me.Skill')),
            ],
            options={
                'db_table': 'PROJECT',
            },
            bases=('me.article',),
        ),
    ]
