# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='me.Article')),
            ],
            options={
                'db_table': 'ABOUT',
            },
            bases=('me.article',),
        ),
        migrations.RemoveField(
            model_name='persona',
            name='about',
        ),
        migrations.AddField(
            model_name='persona',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutme',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.Persona'),
        ),
    ]
