# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_auto_20160616_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='persona',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='me.Persona'),
        ),
    ]
