# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_article_project'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='ARTICLE',
        ),
        migrations.AlterModelTable(
            name='persona',
            table='PERSONA',
        ),
        migrations.AlterModelTable(
            name='project',
            table='PROJECT',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='SKILL',
        ),
    ]
