# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0004_auto_20160616_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='persona',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='aboutme_persona',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='me.Persona'),
        ),
        migrations.AlterModelTable(
            name='aboutme',
            table=None,
        ),
    ]
